spring:
  application:
    name: BOARD-SERVICE
  main:
    allow-bean-definition-overriding: true

server:
  port: 8891

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8888/eureka

